### ISSUE TITLE
operaciones basicas 

### ISSUE THREAD

**Issue by JulioCGz** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-JulioCGz#1]
[operaciones basicas.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-operaciones-basicas-JulioCGz/files/7173830/operaciones.basicas.pdf)

**Comment by Erick-3as** [comment]
esta bueno tu trabajo y buena investigación, te doy 20%

**Comment by josealfredo79** [comment]
Evaluar de acuerdo a la rúbrica

**Comment by Erick-3as** [comment]
Ya lo revise muy bien tus trabajos, te faltaron unas cosas que no venía en la rúbrica, y te doy de calificación de 15% compañero

**Comment by josealfredo79** [comment]
Bien hecho y revisado
